name: AutoDownloader
on:
  workflow_dispatch:
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Aria2 config
      run: |
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
    - name: Init Git
      run: |
        mkdir dir
        cd dir
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
        git config advice.addIgnoredFile false
        git clone ${{ secrets.SERVER }}
    - name: Downloading
      run: |
        cd dir
        aria2c --seed-time=0 -d downloads ${{ secrets.DOWNLOAD }}
    - name: Upload
      run: |
        cd dir
        git add -f downloads
        ls -l
        git clean –fd untracked folder
        git commit -m "upload"
        git remote remove origin
        git add remote origin ${{ secrets.SERVER }}
        git push origin master


