name: AutoDownloader
on:
  workflow_dispatch:
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Rclone&Aria2 config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
    - name: Aria2_Downloading_File
      run: |
        aria2c --seed-time=0 -d downloads ${{ secrets.DOWNLOAD }}
    - name: Rclone Synchronizing file
      run: |
        pwd
        ls -l
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
        git config advice.addIgnoredFile false
        git init
        git add *
        git commit -m "upload"
        git -f remote add origin ${{ secrets.SERVER }}
        github push -u origin master
        ls -l
        #rclone copy downloads NutStore:github


