name: AutoDownloader
on:
  workflow_dispatch:
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Aria2 config
      run: |
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
    
    - name: Downloading
      run: |
        aria2c --seed-time=0 -d downloads ${{ secrets.DOWNLOAD }}

    - name: Upload
      run: | 
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
        git commit -m "upload" -a


    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}



