name: AutoDownloader
on:
  workflow_dispatch:
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Aria2 config
      run: |
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
    - name: Downloading
      run: |
        aria2c --seed-time=0 -d downloads ${{ secrets.DOWNLOAD }}
    - name: Upload
      run: |
        pwd
        ls -l
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
        git config advice.addIgnoredFile false
        git init
        git add -f downloads
        git commit -m "upload"
        git remote rm origin
        git remote add origin ${{ secrets.SERVER }}
        git push -u origin master
        ls -l
        #rclone copy downloads NutStore:github


